openapi: 3.0.3
info:
  title: Condominium management
  description: Basic CRUD operations for persist data about the condominium management
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Condominium management
    description: Basic CRUD operations for persist data about the condominium management
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Create a new user.
      operationId: createUser
      requestBody:
        description: User to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad request
  /apartment/send-proof/{apartmentNumber}:
    post:
      summary: "Upload de comprovante de pagamento"
      parameters:
        - name: "apartmentNumber"
          in: "path"
          required: true
          description: "Número do apartamento para o qual o comprovante será enviado"
          schema:
            type: string
      description: Send payment proof
      operationId: sendProofPayment
      requestBody:
        description: Send image where it is the payment proof
        required: true
        content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  fileProof:
                    type: string
                    format: binary
                  description:
                    type: string

      responses:
        '200':
          description: "Comprovante enviado com sucesso!"
        '204':
          description: "Comprovante enviado com sucesso!"
        '500':
          description: "Erro ao enviar o comprovante"
components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - email
        - phoneNumber
        - apartmentNumber
      properties:
        name:
          type: string
          example: Germano
        email:
          type: string
          example: wanderleco@panelas.pressao
        phoneNumber:
          type: string
          example: (31) 9 0420-0420
        apartmentNumber:
          type: string
          example: 7
    UserResponse:
      type: object
      properties:
        id:
          type: string
          example: f0822b54-0720-11ee-be56-0242ac120002
        name:
          type: string
          example: Germano
        email:
          type: string
          example: wanderleco@panelas.pressao
        phoneNumber:
          type: string
          example: (31) 9 0420-0420
        apartmentNumber:
          type: string
          example: 7