openapi: 3.0.3
info:
  title: Condominium management
  description: |
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Condominium management
    description: Basic CRUD operations for persist data about the condominium management
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: Create a new user.
      operationId: createUser
      requestBody:
        description: User to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad request

components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - email
        - phoneNumber
      properties:
        name:
          type: string
          example: Germano
        email:
          type: string
          example: wanderleco@panelas.pressao
        phoneNumber:
          type: string
          example: (31) 9 0420-0420
    UserResponse:
      type: object
      properties:
        id:
          type: string
          example: f0822b54-0720-11ee-be56-0242ac120002
        name:
          type: string
          example: Germano
        email:
          type: string
          example: wanderleco@panelas.pressao
        phoneNumber:
          type: string
          example: (31) 9 0420-0420