name: Deploy no ambiente de desenvolvimento

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fazendo configuracao do java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Fazendo build do projeto
        run: mvn clean install && ls
      
      - name: Copiando JAR para EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-44-222-140-11.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_JP_PC_EC2 }}
          port: 22
          source: "../target/condominium-manager-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"  
